name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-1:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: DistantMouseCAndroidClient
        path: /home/runner/work/DistantMouseAndroidClient/DistantMouseAndroidClient/app/build/outputs/apk/debug/*.apk
        overwrite: true

  build-2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: DistantMouseCAndroidClient
        path: /home/runner/work/DistantMouseAndroidClient/DistantMouseAndroidClient/app/build/outputs/apk/debug/*.apk
        overwrite: true

  build-3:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'liberica'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: DistantMouseCAndroidClient
        path: /home/runner/work/DistantMouseAndroidClient/DistantMouseAndroidClient/app/build/outputs/apk/debug/*.apk
        overwrite: true

  build-4:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'microsoft'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: DistantMouseCAndroidClient
        path: /home/runner/work/DistantMouseAndroidClient/DistantMouseAndroidClient/app/build/outputs/apk/debug/*.apk
        overwrite: true

  build-5:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: DistantMouseCAndroidClient
        path: /home/runner/work/DistantMouseAndroidClient/DistantMouseAndroidClient/app/build/outputs/apk/debug/*.apk
        overwrite: true

  build-6:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: DistantMouseCAndroidClient
        path: /home/runner/work/DistantMouseAndroidClient/DistantMouseAndroidClient/app/build/outputs/apk/debug/*.apk
        overwrite: true

  build-7:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'dragonwell'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: DistantMouseCAndroidClient
        path: /home/runner/work/DistantMouseAndroidClient/DistantMouseAndroidClient/app/build/outputs/apk/debug/*.apk
        overwrite: true
